spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/appdatabase
  kafka:
    bootstrap-servers: localhost:9092


  app:
    userRegTopic: user-registration
    roomBookingTopic: room-booking
    groupId: statistic_group"

    exportPath: data/export
    fileName: statistic.csv

    photosPath: data/photos