#version: '3'
#
#services:
#  app:
#    image: my-app:latest
#    container_name: spring_app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/app_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    restart: always
#
#  db:
#    image: postgres:latest
#    container_name: postgres_db
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: app_db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data  # Волюм для хранения данных
#
#volumes:
#  postgres_data: